apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web-deployment
  namespace: web-qa
  labels:
    app: devops-web
    environment: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-web
      environment: qa
  template:
    metadata:
      labels:
        app: devops-web
        environment: qa
    spec:
      containers:
        - name: web
          image: devops-web-deployment:qa
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "qa"
            - name: APP_VERSION
              value: "1.0.0-qa"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
